CREATE OR REPLACE PACKAGE BODY PK1 AS


FUNCTION F2(E IN EMP.EMPNO%TYPE,D IN EMP.DEPTNO%TYPE) RETURN BOOLEAN
AS
VDEPTNO EMP.DEPTNO%TYPE;
BEGIN
	SELECT DEPTNO INTO VDEPTNO
	FROM EMP
	WHERE EMPNO = E;
	
	IF(VDEPTNO = D)THEN
		RETURN TRUE;
	ELSE
		RETURN FALSE;
	END IF;
END F2;
PROCEDURE P2(EE IN EMP.EMPNO%TYPE,DD IN EMP.DEPTNO%TYPE) AS
CC NUMBER(3);
FLAG BOOLEAN;
BEGIN
	FLAG := F2(EE,DD);
	IF FLAG THEN
		SELECT COUNT(*) INTO CC FROM EMP WHERE DEPTNO = DD;
	ELSE
		CC := 0;
	END IF;
	DBMS_OUTPUT.PUT_LINE('TOTAL EMPLOYEE ON DEPTNO ' ||TO_CHAR( DD) || ' IS ' ||TO_CHAR(CC));
END P2;
end pk1;
/